1:
  name: EthereumMainnet
  rpcs:
    - "https://ethereum.publicnode.com"
    - "https://rpc.ankr.com/eth"
56:
  name: BNBMainnet
  rpcs:
    - "https://rpc.ankr.com/bsc"
204:
  name: opBNBMainnet
  rpcs:
    - "https://opbnb.publicnode.com"
    - "https://1rpc.io/opbnb"
